//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureCourse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Furniture()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ID_F { get; set; }
        public int ID_C { get; set; }
        public int ID_M { get; set; }
        public int ID_MA { get; set; }
        public string Image { get; set; }
        public decimal Price { get; set; }
        public string CategoryName
        {
            get
            {
                return Category.Category1.ToString();
            }
        }

        public string ManufacturerName
        {
            get
            {
                return Manufacturer.Manufacturer1.ToString();
            }
        }

        public string MaterialName
        {
            get
            {
                return Material.Name.ToString();
            }
        }

        public string Photo
        {
            get
            {
                if (String.IsNullOrEmpty(Image) || String.IsNullOrWhiteSpace(Image))
                {
                    return "/Resources/logo.png";
                }
                else
                {
                    return "/Resources/" + Image;
                }
            }
        }

        public static string AdminControlsVisibility
        {
            get
            {
                if (App.CurrentUser.ID_R == 2)
                {
                    return "Collapsed";
                }
                else
                {
                    return "Visible";
                }
            }
        }

        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Material Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
