//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureCourse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID_O { get; set; }
        public int ID_U { get; set; }
        public int ID_F { get; set; }
        public decimal Price { get; set; }
    
        public virtual Furniture Furniture { get; set; }
        public virtual User User { get; set; }
    }
}
